### ISSUE TITLE
[BUG - Release 0.6]

### ISSUE THREAD

**Issue by remiliascarlet666** [WistfulHopes/RE-UE4SS#6]
**Branch or Release**
[Release - 0.6]

**Game and Engine Version**
Guilty Gear Strive version 1.24

**Describe the bug**
Sigscan error on launch, in game there are no hitboxes and the advantage row shows the word "advantage" but does not show any frame data afterwards. 

**To Reproduce**
1. Install the latest version 0.6 as described
2. Attempt to launch the game
3. See error 

**Expected behavior**
Sigscan error should not happen, and hitboxes and frame data should be viewable in game. Version 0.5.1 and before do not exhibit this behavior 

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Previous versions work fine, latest version does not work as packaged. Maybe the incorrect mods in the StriveHitboxes.rar file were shipped?

**Comment by cweinberg32** [comment]
I am having this same issue, down to the context.

**Comment by cweinberg32** [comment]
[18:16:30] Setting up mods...
[18:16:33] Failed to load dll <C:\Program Files (x86)\Steam\steamapps\common\GUILTY GEAR STRIVE\RED\Binaries\Win64\Mods\StriveHitboxes\dlls\main.dll> for mod StriveHitboxes, error code: 0x45a[18:16:33] Was unable to install mod 'StriveHitboxes' for unknown reasons. Mod is not installable. <-- From the Log File of GGST-Win64-Shipping.exe

**Comment by narknon** [comment]
Send the entire log

**Comment by cweinberg32** [comment]
[UE4SS.log](https://github.com/WistfulHopes/RE-UE4SS/files/11314498/UE4SS.log)

**Comment by WistfulHopes** [comment]
_should_ be fixed now

**Comment by remiliascarlet666** [comment]
Unfortunately 0.6.1 did not solve the issue for me, no changes at all and 0.5.1 and before still work as intended.
I notice that in 0.5.1 and below, the filesize for UE4SS_StriveHitboxes.zip is around 15.3 MB, while 0.6 and afterwards are around 2.49 MB. When unzipped, 0.5.1 is 59 MB while 0.6 and above is around 7.19 MB. The only thing removed was the xinput1_3.pdb file, could this have anything to do with it?

**Comment by WistfulHopes** [comment]
the pdb is for debugging purposes only

i'll try to fix it tomorrow
